MvcCart/MvcCart/Models/Cart.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace MvcCart.Models
{
    public class Cart
    {
        public int Id { get; set; }  //id

        [Required(ErrorMessage = "购物车id必填")]
        [Display(Name = "购物车id")]
        public int cart_id { get; set; }  //购物车id

        [Required(ErrorMessage = "商品id必填")]
        [Display(Name = "商品id")]
        public int product_id { get; set; }  //商品id

        [Display(Name = "商品名称")]
        public string? product_name { get; set; }//商品名称

        [Required(ErrorMessage = "商品数量必填")]
        [Display(Name = "商品数量")]
        public int product_num { get; set; }  //商品数量

        [Required(ErrorMessage = "商品价格必填")]
        [Display(Name = "商品价格")]
        public double product_price { get; set; }  //商品价格

        [Required(ErrorMessage = "用户id必填")]
        [Display(Name = "用户id")]
        public int user_id { get; set; } //用户id

        [Required(ErrorMessage = "创建时间必填")]
        [Display(Name = "创建时间")]
        public DateTime createtime { get; set; } //创建时间


    }
}

MvcCart/MvcCart/Models/ErrorViewModel.cs
namespace MvcCart.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCart/MvcCart/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcCart.Data;
using MvcCart.Models;

namespace MvcCart.Controllers
{
    public class CartsController : Controller
    {
        private readonly MvcCartContext _context;

        public CartsController(MvcCartContext context)
        {
            _context = context;
        }

        // GET: Carts
        /*        public async Task<IActionResult> Index()
                {
                      return _context.Cart != null ? 
                                  View(await _context.Cart.ToListAsync()) :
                                  Problem("Entity set 'MvcCartContext.Cart'  is null.");
                }*/

        public async Task<IActionResult> Index(int? productId, double? low, double? high)
        {
            if (low == null) { low = 0.0; }
            if (high == null) { high = 999.0; }
            if (productId == null) {
                var cart = from c in _context.Cart
                           where low <= c.product_price
                           && high >= c.product_price
                           select c;
                return View(await cart.ToListAsync());
            }
            else
            {
                var cart = from c in _context.Cart
                           where (c.product_id == productId) && low <= c.product_price
                           && high >= c.product_price
                           select c;
                return View(await cart.ToListAsync());
            }
            
        }
        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cart == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,cart_id,product_id,product_name,product_num,product_price,user_id,createtime")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cart == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,cart_id,product_id,product_name,product_num,product_price,user_id,createtime")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cart == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cart == null)
            {
                return Problem("Entity set 'MvcCartContext.Cart'  is null.");
            }
            var cart = await _context.Cart.FindAsync(id);
            if (cart != null)
            {
                _context.Cart.Remove(cart);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
          return (_context.Cart?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MvcCart/MvcCart/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCart.Models;
using System.Diagnostics;

namespace MvcCart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCart/MvcCart/Views/Carts/Create.cshtml
@model MvcCart.Models.Cart

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="cart_id" class="control-label"></label>
                <input asp-for="cart_id" class="form-control" />
                <span asp-validation-for="cart_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_id" class="control-label"></label>
                <input asp-for="product_id" class="form-control" />
                <span asp-validation-for="product_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_name" class="control-label"></label>
                <input asp-for="product_name" class="form-control" />
                <span asp-validation-for="product_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_num" class="control-label"></label>
                <input asp-for="product_num" class="form-control" />
                <span asp-validation-for="product_num" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_price" class="control-label"></label>
                <input asp-for="product_price" class="form-control" />
                <span asp-validation-for="product_price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="user_id" class="control-label"></label>
                <input asp-for="user_id" class="form-control" />
                <span asp-validation-for="user_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="createtime" class="control-label"></label>
                <input asp-for="createtime" class="form-control" />
                <span asp-validation-for="createtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCart/MvcCart/Views/Carts/Delete.cshtml
@model MvcCart.Models.Cart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cart_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cart_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_num)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_num)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.user_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.user_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.createtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.createtime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcCart/MvcCart/Views/Carts/Details.cshtml
@model MvcCart.Models.Cart

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cart_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cart_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_num)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_num)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product_price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product_price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.user_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.user_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.createtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.createtime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcCart/MvcCart/Views/Carts/Edit.cshtml
@model MvcCart.Models.Cart

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="cart_id" class="control-label"></label>
                <input asp-for="cart_id" class="form-control" />
                <span asp-validation-for="cart_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_id" class="control-label"></label>
                <input asp-for="product_id" class="form-control" />
                <span asp-validation-for="product_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_name" class="control-label"></label>
                <input asp-for="product_name" class="form-control" />
                <span asp-validation-for="product_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_num" class="control-label"></label>
                <input asp-for="product_num" class="form-control" />
                <span asp-validation-for="product_num" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="product_price" class="control-label"></label>
                <input asp-for="product_price" class="form-control" />
                <span asp-validation-for="product_price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="user_id" class="control-label"></label>
                <input asp-for="user_id" class="form-control" />
                <span asp-validation-for="user_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="createtime" class="control-label"></label>
                <input asp-for="createtime" class="form-control" />
                <span asp-validation-for="createtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCart/MvcCart/Views/Carts/Index.cshtml
@model IEnumerable<MvcCart.Models.Cart>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Carts" asp-action="Index" method="get">
    <p>
        商品id:
        <input type="text" name="productId">
        物价区间：
        <input type="text" name="low" style="width:60px;"> - <input type="text" name="high" style="width:60px;">
        <input type="submit" value="查询" />
    </p>
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cart_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_num)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.user_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.createtime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cart_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product_num)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product_price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.user_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.createtime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCart/MvcCart/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCart/MvcCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCart.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>